### ISSUE TITLE
What is the licence of this work

### ISSUE THREAD

**Issue by hofingermarkus** [cv-stuttgart/MS_RAFT_plus#1]
Hi,

cool work - thank you for sharing your code! :)
You provided the license for the RAFT part that you used, but what is the license for your own part?
BSD-3 like RAFT or MIT, or something else?

Best Regards, 
Markus

**Comment by az-ja** [comment]
Hi,

Thanks.
We added the license to the repo. It is now mentioned in the README.

Sincerely,
Azin
