### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by TwiceMao** [cv-stuttgart/MS_RAFT_plus#2]
@az-ja Thanks for your great work. How to use your method to obtain optical flow on a custom RGB data set? What are the requirements for the data set to use your method?

**Comment by az-ja** [comment]
Hi,
There are no specific requirements. You can simply read the RGB images and compute the flow using MS-RAFT+.
You should just pad the images, in a way that their height and width are divisible by 16.
You can check out evaluate.py for examples of computing the flow for different datasets.

Regards,
Azin

**Comment by TwiceMao** [comment]
Thanks~
