### ISSUE TITLE
training dataset mixture implementation

### ISSUE THREAD

**Issue by starsong98** [cv-stuttgart/MS_RAFT_plus#4]
Hello, thank you for sharing your code. I have one question about a small aspect of your training code.

RAFT and many of its inspired papers implement dataset mixture by repeating and combining its file lists into one giant dataloader.

In RAFT's case, it is 100 * sintel-clean + 100 * sintel-final + 200 * kitti2015 + 1 * things-clean + 5 * hd1k,
resulting a mixture that consists of approximately 70.9% Sintel, 13.6% KITTI-2015, 13.7% FlyingThings-clean, and 1.78% HD1k.

Was MS-RAFT+'s 'mixed' training ratio implemented similarly? If so, what were the mixing coefficients?
The closest I managed to get to the paper's ratios of 30% Sintel, 28% KITTI, 2% HD1k, 30% VIPER, and 10% FlyingThings3D was through:
58 * sintel-clean + 58 * sintel-final + 560 * kitti-2015 + 9 * viper + 1 * things-clean + 7 * hd1k

which yielded:
30.14% Sintel; 27.96% KITTI; 1.83% HD1k; 30.01% VIPER; 10.06% FlyingThings

but I just wanted to be sure.

Thank you!

**Comment by az-ja** [comment]
Hello,

Here is the exact mix we used for our mixed fine-tuning:
train_dataset = 800 * kitti + 10 * hd1k + 100 * sintel_final + 70 * sintel_clean + 12 * viper + things_clean

Our experiments showed that adding more final pass for the Sintel dataset helped in our case.

With kind regards,
Azin

**Comment by starsong98** [comment]
Thank you!
